---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "[Benjamin G. Brinkerhoff]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Introduction

<!-- highlight line 31 to the end and use ctrl + / (win) or command + / (mac) to uncomment out the code below, the same shortcut can be used to comment out code again. -->

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px

px.scatter(x = [7,8,9,10,11,12], y = [6,5,4,3,2,1], title = "Imports are working")
```


### Elevator pitch

_This metric measures the engines of cars that are made throughout the years making this data vital for any car manufacturer or even the everyday driver. It cannot be overstated how important it is for the everyday driver to know what his or her car is capable of. This data will also help car manufacture companies have more accurate marketting and give them a good idea of where their cars sit on the scale._


```{python}
#| label: project-data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```


### QUESTION|TASK 1

__Finish the readings, setup, and be prepared with any questions to get your environment working smoothly (class for on-campus and Slack for online)__

_Yes, everything seems to work smoothly, this class still makes little sense and I barely made it out of this assignment with my sanity intact; it took forever to connect the dots of what I was both expected to do, and where to even start._


```{python}
#| label: Q1-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here

# Sample code built into the project, but as the only thing needed is a "Yes everything works fine." Having an example graph to prove it isn't a bad idea.
chart = px.scatter(df.head(200),
    x="name", 
    y="AK"
)
chart
```


### QUESTION|TASK 2

__In VS Code, create the example chart from section 3.2.2 of the textbook. (Note: you will be using Plotly Express to display the chart instead of Altair which is used in the book)__

_The results seem to go downwards in terms of "hwy" but then become scattered as "displ" gets better_


```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here

# The actual code sample that I wrote to display a scatter plot of the graph represented in the textbook section 3.2.2 

# If I did this wrong or I'm using the project0.qmd file incorrectly please let me know, everyone on Slack is being irresponsive and I'm struggling to make sense of this class.


url = "https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/mpg/mpg.csv" # We get these values from a csv file online

mpg = pd.read_csv(url) # We load those values into a variable and then convert it to a chart using plotly.
px.scatter(mpg, x=mpg.displ, y=mpg.hwy)

```


### QUESTION|TASK 3

__Your final report should also include the table created from the following (assuming you have mpg from question 2)__

_Most of the results seem to come from aroudn the lat 90's or the late 2001's so fuel usage as shown in Q2 seems to be centralized around that time period._



```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here

# I assume this is what we needed to type in according to the instructions?
(mpg
  .head(5)
  .filter(["manufacturer", "model","year", "hwy"])
)

```

<!-- ```{python}
#| label: Q3-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = px.bar(df.head(200),
    x="name", 
    y="AK"
)
chart.show()
```

_REMOVE ME: the output of any code cell will appear below the cell, including tables and charts_

```{python}
#| label: Q3-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

``` 
_REMOVE ME: the output of any code cell will appear below the cell, including tables and charts_ -->
